name: 'Pack Neon Library'
description: 'Pack and optionally publish a Neon library.'
inputs:
  working-directory:
    description: 'Working directory to run commands from, relative to repo root.'
    required: false
    default: '.'
  output-directory:
    description: 'Putput directory for the tarball, relative to working-directory (created if necessary).'
    required: false
    default: 'dist'
  npm-publish:
    description: 'Publish tarball to npm.'
    required: false
    default: false
  github-release:
    description: 'Publish tarball to GitHub releases.'
    required: false
    default: false
  node-version:
    description: 'Node version number.'
    required: false
    default: ''
branding:
  icon: 'package'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Node
      if: ${{ inputs['node-version'] != '' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: npm
    - name: Install Node
      if: ${{ inputs['node-version'] == '' }}
      uses: actions/setup-node@v3
      with:
        cache: npm
    - name: Install Dependencies
      shell: bash
      run: npm install
      working-directory: ${{ inputs['working-directory'] }}
    - name: Pack
      shell: bash
      run: |
        mkdir -p dist
        npm pack --pack-destination=${{ inputs['output-directory'] }}
      working-directory: ${{ inputs['working-directory'] }}
    - name: Diagnostics
      shell: bash
      run: |
        echo ${{ inputs['github-release'] }}
        echo ${{ inputs['node-version'] }}
        echo ${{ inputs['npm-publish'] }}
    - name: Release
      if: ${{ inputs['github-release'] == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ inputs['working-directory'] }}/${{ inputs['output-directory'] }}/*.tgz
    - name: Publish
      if: ${{ inputs['npm-publish'] == 'true' }}
      shell: bash
      run: npm publish
      working-directory: ${{ inputs['working-directory'] }}
